pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/sarwar-max/react-aws-nginx.git'
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                    archiveArtifacts(artifacts: '**/build/**', fingerprint: true)
                }
            }
        }

        stage('Publish to Artifactory') {
            steps {
                rtServer(
                    id: 'Artifactory',
                    url: 'http://3.142.248.191:8082/artifactory',
                    username: 'sarwar',
                    password: 'Sarwar@1#',
                    bypassProxy: true,
                    timeout: 300
                )

                rtUpload(
                    serverId: 'Artifactory',
                    spec: '''{
                        "files": [
                            {
                                "pattern": "**/build/**",
                                "target": "libs-snapshot-local"
                            }
                        ]
                    }'''
                )
            }
        }

        stage('Deploy to Nginx') {
            steps {
                sh 'mkdir -p ~/.ssh'
                sh 'ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""'
                sh 'chmod 600 ~/.ssh/id_rsa'
                sh 'ssh-copy-id -i ~/.ssh/id_rsa sammy@18.119.121.70'
                sh 'scp -r -i ~/.ssh/id_rsa ./frontend/build sammy@18.119.121.70:/var/www/html'
            }
        }
    }

    post {
        success {
            rtPublishBuildInfo(serverId: 'Artifactory')
        }
    }
}
